### ISSUE TITLE
string does not contain definition for DoSizeFormat()

### ISSUE THREAD

**Issue by mcpdeveloper443** [briandorey/summernote-c-sharp-file-browser#1]
Hi ,

I am getting error in below line :

**Error : string does not contain definition for DoSizeFormat()**

dro[2] = Files[i].Length.ToString().**DoSizeFormat();**

**How to solve this.**  Thanks for your help ahead.

**Comment by briandorey** [comment]
This is the missing function:

public static string DoSizeFormat(this String inval)
        {
            decimal filesize = System.Convert.ToDecimal(inval);
            string displayvalue = "";
            if (filesize >= 1073741824)
            {
                displayvalue = (filesize / 1024 / 1024 / 1024).ToString("F") + " GB";
            }
            if (filesize >= 1048576)
            {
                displayvalue = (filesize / 1024 / 1024).ToString("F") + " MB";
            }
            if (filesize >= 1024)
            {
                displayvalue = (filesize / 1024).ToString("F") + " KB";
            }
            if (filesize < 1024)
            {
                displayvalue = (filesize).ToString("F") + " B";
            }
            return displayvalue;
        }

**Comment by mcpdeveloper443** [comment]
Hi ,

I hope also this i need to be updated 

**from** 
dro[2] = Files[i].Length.ToString().DoSizeFormat();  

**to** 

dro[2] = DoSizeFormat(Files[i].Length.ToString());

**Comment by mcpdeveloper443** [comment]
Hi @briandorey ,

Also is any memory leak or any other issue with this files ?

when i include these file , in a few seconds my application is broken with below error 👍 

**System.Data.SqlServerCe.SqlCeException: 'Native components of SQL Server Compact engine are not loaded. Please reinstall Microsoft SQL Server Compact.'**

If i exclude those file , my application is running perfect , what could be issue please
